covid/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path("accounts/", views.NewAccount, name="new-account"),
    path('', include("django.contrib.auth.urls")),
    ]

dashboard/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

'''
each url is connected to a view, which is the http response
'''
app_name = 'dashboard'

urlpatterns = [
	#/dashboard/
	path('', views.DashboardView.as_view(), name='dash'),
	path('upload-nation-csv/', views.national_data_upload, name='national_data_upload'),
	path('upload-state-csv/', views.state_data_upload, name='state_data_upload'),
	path('National/', views.NationalTableView.as_view(), name='national-List'),
	path('State/', views.StateTableView.as_view(), name='state-List'),
	path('National/<int:pk>/', views.NationalDetailView.as_view(), name="national-detail"),
	path('State/<int:pk>/', views.StateDetailView.as_view(), name='state-detail'),
	path('National/<int:pk>/update/', views.NationalUpdateView.as_view(), name='national-update'),
	path('State/<int:pk>/update/', views.StateUpdateView.as_view(), name='state-update'),
	path('National/create/', views.NationalCreateView.as_view(), name='national-create'),
	path('State/create/', views.StateCreateView.as_view(), name='state-create'),
	path('National/<int:pk>/delete/', views.NationalDeleteView.as_view(), name='national-delete'),
	path('State/<int:pk>/delete/', views.StateDeleteView.as_view(), name='state-delete'),
	
	path('donations/', views.DonationsView, name='donations'),

	path('api/statechart1/data', views.StateChartData1.as_view(), name='api-statechart1-data'),
	path('api/nationalchart1/data', views.NationalChartData1.as_view(), name='api-nationalchart1-data'),
	path('api/statechart2/data', views.StateChartData2.as_view(), name='api-statechart2-data'),
	path('api/nationalchart2/data', views.NationalChartData2.as_view(), name='api-nationalchart2-data'),


]

dashboard/models.py
from django.db import models
from django.urls import reverse
import django_tables2 as tables

class National(models.Model):
	date = models.DateField(max_length=11)
	death = models.IntegerField(default=0)
	deathIncrease = models.IntegerField(default=0)
	InIcuCumulative = models.IntegerField(default=0)
	InIcuCurrently = models.IntegerField(default=0)
	hospitalizedIncrease = models.IntegerField(default=0)
	hospitalizedCurrently = models.IntegerField(default=0)
	hospitalizedCumulative = models.IntegerField(default=0)
	negative = models.IntegerField(default=0)
	negativeIncrease = models.IntegerField(default=0)
	onVentilatorCumulative = models.IntegerField(default=0)
	onVentilatorCurrently = models.IntegerField(default=0)
	positive = models.IntegerField(default=0)
	positiveIncrease = models.IntegerField(default=0)
	states = models.IntegerField(default=0)
	totalTestResults = models.IntegerField(default=0)
	totalTestResultIncrease = models.IntegerField(default=0)

	@classmethod
	def get_expected_names(clas):
		return ['date', 'death', 'deathIncrease', 'InIcuCumulative', 'InIcuCurrently', 'hospitalizedIncrease', 'hospitalizedCurrently', 'hospitalizedCumulative', 'negative', 'negativeIncrease', 'onVentilatorCumulative',
				'onVentilatorCurrently', 'positive', 'positiveIncrease', 'states', 'totalTestResults', 'totalTestResultsIncrease']

	def get_date(self):
		return self.date

	def get_death(self):
		return self.deathIncrease


			


# class NationalTable(tables.Table):
# 	class Meta:
# 		model = National




class State(models.Model):
	date = models.DateField()
	state = models.CharField(max_length=2)
	dataQualityGrade = models.CharField(max_length=2)
	death = models.IntegerField(default=0)
	deathConfirmed = models.IntegerField(default=0)
	deathIncrease = models.IntegerField(default=0)
	deathProbable = models.IntegerField(default=0)
	hospitalized = models.IntegerField(default=0)
	hospitalizedCumulative = models.IntegerField(default=0)
	hospitalizedCurrently = models.IntegerField(default=0)
	hospitalizedIncrease = models.IntegerField(default=0)
	inIcuCumulative = models.IntegerField(default=0)
	inIcuCurrently = models.IntegerField(default=0)
	negative = models.IntegerField(default=0)
	negativeIncrease = models.IntegerField(default=0)
	negativeTestsAntibody = models.IntegerField(default=0)
	negativeTestsPeopleAntibody = models.IntegerField(default=0)
	negativeTestsViral = models.IntegerField(default=0)	
	onVentilatorCumulative = models.IntegerField(default=0)
	onVentilatorCurrently = models.IntegerField(default=0)
	positive = models.IntegerField(default=0)
	positiveCasesViral = models.IntegerField(default=0)	
	positiveIncrease = models.IntegerField(default=0)	
	positiveScore = models.IntegerField(default=0)	
	positiveTestsAntibody = models.IntegerField(default=0)	
	positiveTestsAntigen = models.IntegerField(default=0)	
	positiveTestsPeopleAntibody = models.IntegerField(default=0)	
	positiveTestsPeopleAntigen = models.IntegerField(default=0)	
	positiveTestsViral = models.IntegerField(default=0)	
	recovered = models.IntegerField(default=0)
	totalTestEncountersViral = models.IntegerField(default=0)	
	totalTestEncountersViralIncrease = models.IntegerField(default=0)	
	totalTestResults = models.IntegerField(default=0)	
	totalTestResultsIncrease = models.IntegerField(default=0)	
	totalTestsAntibody = models.IntegerField(default=0)	
	totalTestsAntigen = models.IntegerField(default=0)	
	totalTestsPeopleAntibody = models.IntegerField(default=0)	
	totalTestsPeopleAntigen = models.IntegerField(default=0)	
	totalTestsPeopleViral = models.IntegerField(default=0)	
	totalTestsPeopleViralIncrease = models.IntegerField(default=0)	
	totalTestsViral = models.IntegerField(default=0)	
	totalTestsViralIncrease = models.IntegerField(default=0)

	# class Meta:
	# 	unique_together = ['state', 'date']



	@classmethod
	def get_expected_names(clas):
		return ['date',
				'state',
				'dataQualityGrade',
				'death',
				'deathConfirmed',
				'deathIncrease',
				'deathProbable',
				'hospitalized',
				'hospitalizedCumulative',
				'hospitalizedCurrently',
				'hospitalizedIncrease',
				'inIcuCumulative',
				'inIcuCurrently',
				'negative',
				'negativeIncrease',
				'negativeTestsAntibody',
				'negativeTestsPeopleAntibody',
				'negativeTestsViral',
				'onVentilatorCumulative',
				'onVentilatorCurrently',
				'positive',
				'positiveCasesViral',
				'positiveIncrease',
				'positiveScore',
				'positiveTestsAntibody',
				'positiveTestsAntigen',
				'positiveTestsPeopleAntibody',
				'positiveTestsPeopleAntigen',
				'positiveTestsViral',
				'recovered',
				'totalTestEncountersViral',
				'totalTestEncountersViralIncrease',	
				'totalTestResults', 
				'totalTestResultsIncrease',
				'totalTestsAntibody',
				'totalTestsAntigen', 
				'totalTestsPeopleAntibody',
				'totalTestsPeopleAntigen',
				'totalTestsPeopleViral',
				'totalTestsPeopleViralIncrease',
				'totalTestsViral',
				'totalTestsViralIncrease'
				]



# class StateTable(tables.Table):
# 	class Meta:
# 		model = State















			

dashboard/forms.py
from django import forms
from .models import National, State

class NationalForm(forms.ModelForm):

	class Meta:
		model = National



class StateForm(forms.ModelForm):

	class Meta:
		model = State

dashboard/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (ListView, DetailView, UpdateView, DeleteView, CreateView)
from .models import National, State
from .tables import NationalTable, StateTable, NationalTableLI, StateTableLI
from datetime import datetime
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import LoginRequiredMixin
import csv,  io
from django_filters.views import FilterView
from django_tables2 import SingleTableView
from django_tables2.views import MultiTableMixin
from django.contrib import messages
from .filters import NationalFilter
from django.contrib.admin.views.decorators import staff_member_required
from rest_framework.views import APIView 
from rest_framework.response import Response 
from django.db.models import Sum, Max
from django.db.models.functions import TruncMonth


def DonationsView(request):
	return render(request, 'dashboard/donations.html', {})


class DashboardView(SingleTableView):
	template_name = 'dashboard/dash.html'
	model = National
	table_class = NationalTable


class NationalTableView(SingleTableView, FilterView):
	model = National
	template_name = "dashboard/national_list.html"

	filter_class = NationalFilter
	#only give users the option to see the details of the data, and thus update or delete
	def get_table_class(self):
		if self.request.user.is_authenticated:
			print("not here")
			return NationalTableLI
		else:
			print("here")
			return NationalTable


class StateTableView(SingleTableView):
	table_class = StateTable

	model = State
	template_name = "dashboard/state_list.html"
	#only give users the option to see the details of the data, and thus update or delete
	def get_table_class(self):
		if self.request.user.is_authenticated:
			print("not here")
			return StateTableLI
		else:
			print("here")
			return StateTable

class NationalDetailView(LoginRequiredMixin, DetailView):
	login_url = '/login/'
	redirect_field_name = 'login'
	model = National
	fields = ['date',
			'death',
			'deathIncrease',
			'InIcuCumulative',
			'InIcuCurrently',
			'hospitalizedIncrease',
			'hospitalizedCurrently',
			'hospitalizedCumulative',
			'negative',
			'negativeIncrease',
			'onVentilatorCumulative',
			'onVentilatorCurrently',
			'positive',
			'positiveIncrease',
			'states',
			'totalTestResults',
			'totalTestResultIncrease',
			]
	template_name = "dashboard/national_detail.html"

class StateDetailView(LoginRequiredMixin, DetailView):
	login_url = '/login/'
	redirect_field_name = 'login'
	model = State
	fields = ['date',
				'state',
				'dataQualityGrade',
				'death',
				'deathConfirmed',
				'deathIncrease',
				'deathProbable',
				'hospitalized',
				'hospitalizedCumulative',
				'hospitalizedCurrently',
				'hospitalizedIncrease',
				'inIcuCumulative',
				'inIcuCurrently',
				'negative',
				'negativeIncrease',
				'negativeTestsAntibody',
				'negativeTestsPeopleAntibody',
				'negativeTestsViral',
				'onVentilatorCumulative',
				'onVentilatorCurrently',
				'positive',
				'positiveCasesViral',
				'positiveIncrease',
				'positiveScore',
				'positiveTestsAntibody',
				'positiveTestsAntigen',
				'positiveTestsPeopleAntibody',
				'positiveTestsPeopleAntigen',
				'positiveTestsViral',
				'recovered',
				'totalTestEncountersViral',
				'totalTestEncountersViralIncrease',	
				'totalTestResults', 
				'totalTestResultsIncrease',
				'totalTestsAntibody',
				'totalTestsAntigen', 
				'totalTestsPeopleAntibody',
				'totalTestsPeopleAntigen',
				'totalTestsPeopleViral',
				'totalTestsPeopleViralIncrease',
				'totalTestsViral',
				'totalTestsViralIncrease'
			]
	template_name = "dashboard/state_detail.html"


class NationalDeleteView(LoginRequiredMixin, DeleteView):
	login_url = '/login/'
	redirect_field_name = 'login'
	success_url = reverse_lazy('dashboard:national-List')
	model = National
	template_name = "dashboard/national_delete.html"

class StateDeleteView(LoginRequiredMixin, DeleteView):
	login_url = '/login/'
	redirect_field_name = 'login'
	success_url = reverse_lazy('dashboard:state-List')
	model = State
	template_name = "dashboard/state_delete.html"

class NationalCreateView(LoginRequiredMixin, CreateView):
	login_url = '/login/'
	redirect_field_name = 'login'
	model = National
	success_url = reverse_lazy('dashboard:national-List')
	template_name = "dashboard/national_create.html"
	fields = ['date',
			'death',
			'deathIncrease',
			'InIcuCumulative',
			'InIcuCurrently',
			'hospitalizedIncrease',
			'hospitalizedCurrently',
			'hospitalizedCumulative',
			'negative',
			'negativeIncrease',
			'onVentilatorCumulative',
			'onVentilatorCurrently',
			'positive',
			'positiveIncrease',
			'states',
			'totalTestResults',
			'totalTestResultIncrease',
			]

class StateCreateView(LoginRequiredMixin, CreateView):
	login_url = '/login/'
	redirect_field_name = 'login'
	model = State
	success_url = reverse_lazy('dashboard:state-List')
	template_name = "dashboard/national_create.html"
	fields = ['date',
				'state',
				'dataQualityGrade',
				'death',
				'deathConfirmed',
				'deathIncrease',
				'deathProbable',
				'hospitalized',
				'hospitalizedCumulative',
				'hospitalizedCurrently',
				'hospitalizedIncrease',
				'inIcuCumulative',
				'inIcuCurrently',
				'negative',
				'negativeIncrease',
				'negativeTestsAntibody',
				'negativeTestsPeopleAntibody',
				'negativeTestsViral',
				'onVentilatorCumulative',
				'onVentilatorCurrently',
				'positive',
				'positiveCasesViral',
				'positiveIncrease',
				'positiveScore',
				'positiveTestsAntibody',
				'positiveTestsAntigen',
				'positiveTestsPeopleAntibody',
				'positiveTestsPeopleAntigen',
				'positiveTestsViral',
				'recovered',
				'totalTestEncountersViral',
				'totalTestEncountersViralIncrease',	
				'totalTestResults', 
				'totalTestResultsIncrease',
				'totalTestsAntibody',
				'totalTestsAntigen', 
				'totalTestsPeopleAntibody',
				'totalTestsPeopleAntigen',
				'totalTestsPeopleViral',
				'totalTestsPeopleViralIncrease',
				'totalTestsViral',
				'totalTestsViralIncrease'
			]


class NationalUpdateView(LoginRequiredMixin, UpdateView):
	login_url = '/login/'
	redirect_field_name = 'login'
	model = National
	success_url = reverse_lazy('dashboard:national-List')
	template_name = "dashboard/national_update.html"

	fields = ['date',
			'death',
			'deathIncrease',
			'InIcuCumulative',
			'InIcuCurrently',
			'hospitalizedIncrease',
			'hospitalizedCurrently',
			'hospitalizedCumulative',
			'negative',
			'negativeIncrease',
			'onVentilatorCumulative',
			'onVentilatorCurrently',
			'positive',
			'positiveIncrease',
			'states',
			'totalTestResults',
			'totalTestResultIncrease',
			]


class StateUpdateView(LoginRequiredMixin, UpdateView):
	model = State
	template_name = "dashboard/state_update.html"
	success_url = reverse_lazy('dashboard:state-List')
	fields = ['date',
				'state',
				'dataQualityGrade',
				'death',
				'deathConfirmed',
				'deathIncrease',
				'deathProbable',
				'hospitalized',
				'hospitalizedCumulative',
				'hospitalizedCurrently',
				'hospitalizedIncrease',
				'inIcuCumulative',
				'inIcuCurrently',
				'negative',
				'negativeIncrease',
				'negativeTestsAntibody',
				'negativeTestsPeopleAntibody',
				'negativeTestsViral',
				'onVentilatorCumulative',
				'onVentilatorCurrently',
				'positive',
				'positiveCasesViral',
				'positiveIncrease',
				'positiveScore',
				'positiveTestsAntibody',
				'positiveTestsAntigen',
				'positiveTestsPeopleAntibody',
				'positiveTestsPeopleAntigen',
				'positiveTestsViral',
				'recovered',
				'totalTestEncountersViral',
				'totalTestEncountersViralIncrease',	
				'totalTestResults', 
				'totalTestResultsIncrease',
				'totalTestsAntibody',
				'totalTestsAntigen', 
				'totalTestsPeopleAntibody',
				'totalTestsPeopleAntigen',
				'totalTestsPeopleViral',
				'totalTestsPeopleViralIncrease',
				'totalTestsViral',
				'totalTestsViralIncrease'
			]

#Give only admin users the ability to upload a new CSV
@permission_required('admin.can_add_log_entry')
def national_data_upload(request):

	context = {
		'data': 'upload the data here'
	}

	no_errors = True
	if request.method == "GET":
		return render(request, "dashboard/national_data_upload.html", context)


	tmp_file = request.FILES['file']

	#verify the file is CSV format
	if no_errors:
		if not tmp_file.name.endswith('.csv'):
			no_errors = False
			messages.error(request, "incorrect file type")

	data_set = tmp_file.read().decode('UTF-8')


	io_string = io.StringIO(data_set)

	new_names = []
	for row in csv.reader(io_string, delimiter = ',') : 
		new_names.extend(row) 
		break


	expected_names = National.get_expected_names()
	#verifying CSV file is correct length
	if no_errors:
		if (len(expected_names) != len(new_names)):
			no_errors = False
			messages.error(request, "incorrect CSV size")

	#verifying CSV file matches proper table headings
	if no_errors:
		for x in range(len(expected_names)):
			if (expected_names[x] != new_names[x]):
				no_errors = False
				messages.error(request, "incorrect CSV data")
				break


	


	


	if no_errors:
		for col in csv.reader(io_string, delimiter=',', quotechar="|"):
			_, temp = National.objects.update_or_create(
				date = datetime.strptime(col[0], "%Y-%m-%d"),
				death = int(float(col[1])),
				deathIncrease = int(float(col[2])),
				InIcuCumulative = int(float(col[3])),
				InIcuCurrently = int(float(col[4])),
				hospitalizedIncrease = int(float(col[5])),
				hospitalizedCurrently = int(float(col[6])),
				hospitalizedCumulative = int(float(col[7])),
				negative = int(float(col[8])),
				negativeIncrease = int(float(col[9])),
				onVentilatorCumulative = int(float(col[10])),
				onVentilatorCurrently = int(float(col[11])),
				positive = int(float(col[12])),
				positiveIncrease = int(float(col[13])),
				states = int(float(col[14])),
				totalTestResults = int(float(col[15])),
				)

dashboard/templates/dashboard/bootstrap4.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>


<!-- cdn for charts.js-->
<script src='https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js'></script>

<!-- front end linkss for use in other templates -->

dashboard/templates/dashboard/donations.html
{% include 'dashboard/bootstrap4.html' %}
{% include 'dashboard/navbar.html' %}

<style>
.header{
	color: white;
	text-align: center;
	background: #1E90FF;
}
</style>

<div class="header">
	<h1>Looking to Help, Donate to an Organization Below</h1>
</div>




<body>
<div class="row">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Feeding America Covid-19 Response Fund</h5>
        <p class="card-text">As a result of the COVID-19 pandemic, many food pantries have struggled to remain fully stocked, especially as the number of food-insecure people has increase exponentially due to layoffs and national shutdowns. Feeding America started a COVID-19 emergency response fund to ensure their food banks and pantries have enough supplies to respond to the increased demand and help those in need.</p>
        <a href="https://secure.feedingamerica.org/site/Donation2?28371.donation=form1&df_id=28371&mfc_pref=T&s_onsite_promo=take_action&s_src=W204ORGSC&s_referrer=google&s_channel=google&s_subsrc=https%3A%2F%2Fwww.feedingamerica.org%2Ftake-action%2Fcoronavirus&_ga=2.58138858.1164425527.1586352406-808902550.1585936825" class="btn btn-primary">Donate</a>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Meals on Wheels Covid-19 Response Fund</h5>
        <p class="card-text">In light of COVID-19, Meals on Wheels has become increasingly essential, as this organization delivers meals to individuals at home who are unable to purchase or prepare their own food. For those are immune compromised or at higher risk of infection, such as the elderly, Meals on Wheels has been essential for getting through the pandemic. </p>
        <a href="https://ams.mealsonwheelsamerica.org/eweb/DynamicPage.aspx?WebCode=covid19donate&site=mowa&CampCode=COVID-19EmergencyResponseCamp&AplCode=2020ER-POP-UP-COVID-19&_ga=2.149797750.1576770089.1586352634-1817139859.1586352633" class="btn btn-primary">Donate</a>
      </div>
    </div>
  </div>
</div>
&nbsp;
<div class="row">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Habitat for Humanity</h5>
        <p class="card-text">Habitat for Humanity, a nonprofit that helps families in need to build and improve their homes, has released a COVID-19 call-to-action, as millions of Americans face eviction and homelessness due the economic travesty caused by the coronavirus pandemic. Donations to Habitat for Humanity enables this organization to support families and provide them with housing security in this time of uncertainty.</p>
        <a href="https://www.habitat.org/donate/?keyword=menu-top" class="btn btn-primary">Donate</a>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Frontline Impact Project</h5>
        <p class="card-text">The Frontline Impact Project is looking for donations, both of money and supplies, in order to support the dedicated frontline healthcare workers who have put their lives at risk in order to treat those affected by COVID-19. Donations will directly help frontline workers, as well as their families, as it will provide them with necessary resources and support their continued efforts to stop the coronavirus pandemic.</h5>
        <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
        <a href="https://www.frontlineimpact.org/" class="btn btn-primary">Donate</a>
      </div>
    </div>
  </div>
</div>
    

 </body>  

dashboard/templates/dashboard/national_create.html
{% include 'dashboard/navbar.html' %}
{% include 'dashboard/bootstrap4.html' %}
<h3>Create new data entry</h3>



<form method="post">
	{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

dashboard/templates/dashboard/national_data_upload.html
{% include 'dashboard/navbar.html' %}
{% include 'dashboard/bootstrap4.html' %}
{% if messages %}
	{% for message in messages %}
		<div>
			<strong>{{message}}</strong>
		</div>
	{% endfor %}
{% else %}
{{order}}
<form method="post" enctype="multipart/form-data">
	{% csrf_token %}
	<label>Upload the file here</label>
	<input type="file" name="file">
	<p>Only accepts CSV files</p>
	<button type="submit">Upload</button>

</form>
{% endif %}

dashboard/templates/dashboard/national_death_chart.html
{% include 'dashboard/bootstrap4.html' %}


<script>

{% block jquery%}
var endpoint='/api/nationalchart/data'
var defualtData=[]
var labels=[]

$.ajax({
  method: "GET",
  url: endpoint,
  success: function(data) {
    console.log(data)
    defaultData = data.dataView
    labels = data.labelsView
    var ctx= document.getElementById('myChart')
    var myChart = new Chart(ctx, {
      type:'bar',
      data: {
        labels: labels,
        datasets: [{
          label: data.chartLabel,
          data: defaultData 

        }]
      }

    })
  },
  error: function(error_data) {
    console.log
    console.log(error_da)
  }
})

{% endblock %}
</script>

 



<canvas id="myChart" width="400" height="400"></canvas>
<script>
var ctx = document.getElementById('myChart');
</script>

dashboard/templates/dashboard/national_delete.html
{% include 'dashboard/bootstrap4.html' %}
{% include 'dashboard/navbar.html' %}

<style>
	.header {
		background: #1E90FF;
		text-align: left;
		color: white;
		font-family: Arial, sans-serif;
		padding: 10
	}
	h1 {
		font-size: 20px
	}

	
	</style>

<div class="header">
	<h1>Delete Page</h1>
</div>
<form method="post">
	{% csrf_token %}
	<div class="card" style="width: 25rem; height: 10rem, background: blue">
  		<div class="card-body">
    		<h5 class="card-title">Data for US on {{ object.date }}</h5>
    		<p class="card-text">Are you sure you want to delete?</p>
    		<input type="submit" value="Confirm">
    		<a href="/National/{{object.id}}/" class="card-link">cancel</a>
  		</div>
	</div>
</form>

dashboard/templates/dashboard/national_list.html
{% include 'dashboard/bootstrap4.html' %}
{% load render_table from django_tables2 %}
{% include 'dashboard/navbar.html' %}

<html>

<style>
	body {background-color: white}
	h1	{color: blue; text-align: center;}
</style>
	
    <head>
        <title>US National Covid history</title>
        <h1> US National Covid Data</h1>
    </head>
    <body>
        {% render_table table %}
    	
    </body>
</html>

dashboard/templates/dashboard/navbar.html
{% include 'dashboard/bootstrap4.html' %}
{% load static %}

<head>

<style>
	
li {
  float: left;
}

li a {
  display: block;
  color: white;
  text-align: center;
  padding: 14px 20px;
  text-decoration: none;
}

li a:hover {
	background-color: #00BFFF;
}

li a:link {text-decoration: None}

ul {
  
  
  margin: 0;
  padding: 0;
  overflow: hidden;
  background-color: blue;
}



ul a:active { background-color: powderblue}


</style>
</head>

<body>
	<ul>
		
		<li><a href="/">Home Page</a></li>
		<li><a href="/National">National Datatable</a></li>
		<li><a href="/State">State Datatable</a></li>
		<li><a href="/donations">Donations</a></li>
		<!-- <li style="float:right";> <img style='height:5%; width: 5%; object-fit: contain; position: absolute; right: 50%' src="{% static 'dashboard/images/IBM-logo.png'%}" ></li> -->
		<l1 style="float:right;">
			<a href="https://www.ibm.com/impact/covid-19"><img src = "{% static 'dashboard/images/IBM-logo.png'%}" width="60" height="52"/></a></l1>
		{% if request.user.is_authenticated %}
		<li style="float:right;"><a href="/logout">Logout</a></li>
		<li style="float:right;"><a href="{% url 'dashboard:national-create' %}">Add New National Entry</a></li>
		<li style="float:right;"><a href="{% url 'dashboard:state-create' %}">Add New State Entry</a></li>
		{% else %}
		<li style="float:right"><a href="/login">Login</a></li>
		{% endif %}
		
	</ul>

</body>










<!-- nav class="navbar navbar_default">
	<div class="container-fluid">

	<div class="navbar-header">

		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target='navbar'> </button> 

			<a class="dashboard" href="/">Home Page</a>

		</div>


		<div class="collapse navbar-collapse"></div>

	</div>
</nav> -->

dashboard/templates/dashboard/state_create.html
{% include 'dashboard/navbar.html' %}
{% include 'dashboard/bootstrap4.html' %}
<h3>Create new data entry</h3>



<form method="post">
	{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>